apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: oci-storage-initializer
spec:
  container:
    name: storage-initializer
    image: cledge/oci-storage-initializer:v1
    imagePullPolicy: IfNotPresent # NOT FOR PROD but allow easier testing of local images with KinD (just remove for prod)
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
          #      limits:
          # memory: 1Gi
          #  cpu: "1"
  supportedUriFormats:
    - prefix: oci-artifact://

